// Map image ID to description
export const woundDescriptions: Record<string, string> = {
    "wunde_01": "Infizierte abdominale Operationswunde mit Fibrinbelag in der Wundfläche.",
    "wunde_02": "Verbrennungen an Hand und Arm",
    "wunde_03": "Verbrennung am Arm: sauber, aber mit Übergranulation.",
    "wunde_04": "Nekrotische, infizierte Wunde nach einem Insektenstich",
    "wunde_05": "Verbrennung am Bein",
    "wunde_06": "Verbrennung am Fuß",
    "wunde_07": "Zirkumferenzielles, stark exsudierendes Ulkus.",
    "wunde_08": "Extravasionswunde am Fuß eines Säuglings",
    "wunde_09": "Nekrotische Fußwunde infolge einer Ischämie",
    "wunde_10": "Nekrotische Fersenwunde infolge von Ischämie und Druck.",
    "wunde_11": "Nekrotische Fußwunden infolge von Ischämie und Druck",
    "wunde_12": "Wunde an der plantaren Fußfläche infolge von Ischämie und Druck.",
    "wunde_13": "Wunde am Malleolus infolge von Druck und Ischämie.",
    "wunde_14": "Ausgedehnte Wunde am Fußrücken",
    "wunde_15": "Ausgedehnte, tiefe Wunde am Fuß",
    "wunde_16": "Gravitationsulzera bei einem Paraplegiker.",
    "wunde_17": "Mehrere infizierte Fußulzera",
    "wunde_18": "Infizierte Ulzera im Knöchelbereich",
    "wunde_19": "Tiefes Ulkus an der lateralen Fußseite.",
    "wunde_20": "Ulkus an der Ferse und an der plantaren Fußfläche.",
    "wunde_21": "Ausgedehnte feuchte Nekrose an der plantaren Fußfläche mit freiliegenden Sehnen",
    "wunde_22": "Schwarze nekrotische Druckschädigung an der Ferse.",
    "wunde_23": "Kleines, aber tiefes Ulkus an der lateralen Fußseite.",
    "wunde_24": "Große nekrotische Ulzera am Fußrücken.",
    "wunde_25": "Fibrinbelegte Wunde am Fußrücken mit freiliegender Sehne",
    "wunde_26": "Infiziertes ischämisches Ulkus an der lateralen Fußseite.",
    "wunde_27": "Fibrinbelegtes Ulkus an der Ferse, möglicherweise durch Druckschädigung verursacht.",
    "wunde_28": "Großes Ulkus an der Ferse, möglicherweise durch Druckschädigung verursacht",
    "wunde_29": "Hämangiom mit nekrotischem Zentrum am Gesäß eines Säuglings",
    "wunde_30": "Mehrere kleine Beingeschwüre, möglicherweise durch Vaskulitis verursacht",
    "wunde_31": "Ischämisches Ulkus mit fibrösem, fibrinbelegtem Gewebe",
    "wunde_32": "Venöses Ulkus im Zusammenhang mit Adipositas",
    "wunde_33": "Kleines, oberflächliches Beingeschwür mit Fibrinbelag.",
    "wunde_34": "Großes, flaches Ulkus mit zwei Inseln vitalen Gewebes.",
    "wunde_35": "Mehrere kleine Beingeschwüre, möglicherweise durch Vaskulitis verursacht.",
    "wunde_36": "Ein tiefes, ausgestanzt wirkendes Ulkus",
    "wunde_37": "Oberflächliches venöses Ulkus mit ausgeprägtem Fibrinbelag",
    "wunde_38": "Großes oberflächliches venöses Ulkus",
    "wunde_39": "Oberflächliches Beingeschwür mit geringen Mengen an Fibrinbelag.",
    "wunde_40": "Oberflächliches Dekubitalulkus",
    "wunde_41": "Oberflächliches venöses Ulkus mit ausgeprägtem Fibrinbelag.",
    "wunde_42": "Tiefes, ausgestanzt wirkendes Beingeschwür, wahrscheinlich ischämisch und möglicherweise infiziert",
    "wunde_43": "Vereinzelte Maden in einem mit Pseudomonas aeruginosa infizierten Beingeschwür, das grüne Pigmente bildet",
    "wunde_44": "Ausgedehntes, tiefes, mit Fibrin belegtes Beingeschwür.",
    "wunde_45": "Beingeschwür im Zusammenhang mit Adipositas",
    "wunde_46": "Ausgestanzt wirkendes, mit Fibrin gefülltes Ulkus unbekannter Ursache",
    "wunde_47": "Infiziertes, mit Fibrin belegtes Beingeschwür mit freiliegenden Sehnen",
    "wunde_48": "Venöses Ulkus im Zusammenhang mit Adipositas.",
    "wunde_49": "Relativ kleine, aber tiefe Beingeschwüre",
    "wunde_50": "Mit Fibrin belegtes Ulkus über der Achillessehne mit Bildung von Granulationsgewebe",
    "wunde_51": "Dekubitus an der Ferse",
    "wunde_52": "Dekubitus an der Ferse",
    "wunde_53": "Dekubitus an der Ferse",
    "wunde_54": "Massives nekrotisches Dekubitalulkus",
    "wunde_55": "Tiefes Dekubitalulkus",
    "wunde_56": "Tiefes, kleines Dekubitalulkus.",
    "wunde_57": "Fibrinbelegtes sakrales Dekubitalulkus",
    "wunde_58": "Oberflächliches Dekubitalulkus",
    "wunde_59": "Dekubitalulzera mit Ausmaß der Unterminierung.",
    "wunde_60": "Ausgedehnte Druckschädigung."
};

export function getDescription(imageId: string): string {
    return woundDescriptions[imageId] || "Keine Beschreibung verfügbar";
}